INSERT INTO TICKET_TYPE(NAME) VALUES('SPORT');
INSERT INTO TICKET_TYPE(NAME) VALUES('MUSIC');
INSERT INTO TICKET_TYPE(NAME) VALUES('ART');
INSERT INTO TICKET_TYPE(NAME) VALUES('CINEMA');
INSERT INTO TICKET_TYPE(NAME) VALUES('ENTERTAINMENT');
INSERT INTO TICKET_TYPE(NAME) VALUES('TRAVEL');

INSERT INTO TICKET(TYPE_ID, EVENT_NAME, VENUE, DESCRIPTION, EVENT_DATE_TIME, PRICE)
VALUES(1, 'CROATIA - TUNISIA', 'CAIRO', 'INTERNATIONAL FRIENDLY GAME',
       parsedatetime('24-03-2024 12:00', 'dd-MM-yyyy hh:mm'), 50);

INSERT INTO TICKET(TYPE_ID, EVENT_NAME, VENUE, DESCRIPTION, EVENT_DATE_TIME, PRICE)
VALUES(2, 'INMUSIC FESTIVAL', 'ZAGREB', 'SUMMER MUSIC FESTIVAL',
       parsedatetime('24-06-2024 12:00', 'dd-MM-yyyy hh:mm'), 100);

INSERT INTO TICKET(TYPE_ID, EVENT_NAME, VENUE, DESCRIPTION, EVENT_DATE_TIME, PRICE)
VALUES(3, 'NOĆ MUZEJA', 'CROATIA', 'MUSEUMS NIGHT',
       parsedatetime('24-11-2024 12:00', 'dd-MM-yyyy hh:mm'), 0);